### ISSUE TITLE
Final testing sweep

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#169]
Need to do is test with:

* Current latest version browsers (Chrome, FF, Safari)
* Current version -1 browsers (Chrome, FF, Safari) - so if latest is 60 we'll test on 59 as well.

Use Browserstack - https://www.browserstack.com

What we want to cover is pages on the site which use our templates: http://iati.surge.sh/page-templates/ 

* [x] **0-Home** - http://iati.surge.sh/page-templates/0-home
* [x] **01-About** - http://iati.surge.sh/page-templates/01-about
* [x] **01-1-About-Subpage** - http://iati.surge.sh/page-templates/01-1-about-subpage
* [x] **01-1b-About-Subpage-3-Levels** - http://iati.surge.sh/page-templates/01-1b-about-subpage-3-levels
* [x] **01-2-Case-Studies** - http://iati.surge.sh/page-templates/01-2-case-studies
* [x] **01-2-1-Case-Study** - http://iati.surge.sh/page-templates/01-2-1-case-study
* [x] **01-3-Download-Listing** - http://iati.surge.sh/page-templates/01-3-download-listing
* [x] **01-4-People** - http://iati.surge.sh/page-templates/01-4-people
* [x] **01-5-History** - http://iati.surge.sh/page-templates/01-5-history
* [x] **02-1-Guidance-Support** - http://iati.surge.sh/page-templates/02-1-guidance-support
* [x] **02-2-Guidance-Section** - http://iati.surge.sh/page-templates/02-2-guidance-section
* [x] **02-3-Guidance-Single** - http://iati.surge.sh/page-templates/02-3-guidance-single
* [x] **02-4-Guidance-Group** - http://iati.surge.sh/page-templates/02-4-guidance-group
* [x] **03-News** - http://iati.surge.sh/page-templates/03-news
* [x] **03-1-News-Single** - http://iati.surge.sh/page-templates/03-1-news-single
* [x] **04-Events** - http://iati.surge.sh/page-templates/04-events
* [x] **04a-Past-Events** - http://iati.surge.sh/page-templates/04a-past-events
* [x] **04-1-Events-Single** - http://iati.surge.sh/page-templates/04-1-events-single
* [x] **04-1a-Past-Events-Single** - http://iati.surge.sh/page-templates/04-1a-past-events-single
* [x] **04-1b-Past-Events-Single** - http://iati.surge.sh/page-templates/04-1b-past-events-single
* [x] **06-Standard-Page** - http://iati.surge.sh/page-templates/06-standard-page
* [x] **07-Website-Link** - http://iati.surge.sh/page-templates/07-website-link

Can't check these as they're not built out: 

* [ ] **02-6-Knowledgebase-Search-Results** - http://iati.surge.sh/page-templates/02-6-knowledgebase-search-results
* [ ] **02-5-Knowledgebase** - http://iati.surge.sh/page-templates/02-5-knowledgebase
* [ ] **02-6a-Knowledgebase-Search-Zero-Results** - http://iati.surge.sh/page-templates/02-6a-knowledgebase-search-zero-results
* [ ] **02-7-Knowledgebase-Single** - http://iati.surge.sh/page-templates/02-7-knowledgebase-single
* [ ] **08-Using-Iati-Data** - http://iati.surge.sh/page-templates/08-using-iati-data
* [ ] **08-1-Tools-Resources** - http://iati.surge.sh/page-templates/08-1-tools-resources
* [ ] **08-2-Tools-Resources-Single** - http://iati.surge.sh/page-templates/08-2-tools-resources-single

Can't check these as there are no filtering options currently

* [ ] **03a-News-Filtered** - http://iati.surge.sh/page-templates/03a-news-filtered
* [ ] **04a-Events-Filtered** - http://iati.surge.sh/page-templates/04a-events-filtered

Data isn't filled out enough to test properly

* [ ] **05-Contact** - http://iati.surge.sh/page-templates/05-contact

Can't check as debug is on

* [ ] **E1-Error** - http://iati.surge.sh/page-templates/e1-error
* [ ] **E2-500** - http://iati.surge.sh/page-templates/e2-500

**Comment by sargentfrancesca** [comment]
**Template:**

**Chrome 67**

* [ ] Validation
* [ ] HTML5 
  *  Use this code in a bookmark to validate HTML5 against the current tab
      
      ```
       javascript:void(document.location=’http://html5.validator.nu/? 
       doc='+escape(document.location)+'&showimagereport=yes&showsource=yes'
      ```
* [ ] No JS
* [ ] Breakpoints (Visual Design)
* [ ] Link clicks
* [ ] General visual/matching pattern lib
* [ ] Data
* [ ] Accessibility

**Chrome 66**
**Safari 11.1**
**Firefox 60**
**Firefox 59**
**Android Chrome**
**iPhone 6s safari**

---

## E1 Error ##
* Debugging is enabled on staging, so cannot see 404 page, can't find a debug view for it either.

---

## Home ##

* [x] Validation
  * Validation uses browser validation - is this wanted?
* [x] General visual/matching pattern lib
  * Current active nav item not underlined in menu
  * `basicScroll` JS errors (`Uncaught TypeError: Cannot read property 'track' of null`)
* [x] Data
  * Hero image has no title, caption data, returns `None`
  * Broken links `Explore our data`, `Discover the standard`, `Find out more about IATI`, 
* [x] Accessibility
  * Form elements in sign up form do not have associated labels
  * `<html>` element does not have a `lang` attribute

### Firefox 60 ### 

* [x] Breakpoints
  * above 1280, last digit of statistic jumps down

<img width="1095" alt="screen shot 2018-07-02 at 15 03 28" src="https://user-images.githubusercontent.com/8557782/42230217-4bcafff0-7ee0-11e8-9c69-5d3a3ccf5420.png">


### Firefox 59 ### 

* [x] Breakpoints
  *  above issue doesn't exist

### iPhone 6s safari ### 

* [x] Validation
  * Errors forward to mailchimp - check this is desired

---

## Case study ##

* [x] Breakpoints (Visual Design)
  * Responsive text size (> 1150px) is different to PL, slightly larger
* [x] General visual/matching pattern lib
  * Quote img not present (I'm assuming because one wasn't added in CMS, but won't completely assume)
  * Content box is smaller than PL
* [x] Data
  * Graph is placeholder, does not link

---

## People ##

* [x] General visual/matching pattern lib
  * Fallback image used for logo, logo field is not required, will this placeholder change? (http://staging2.iatistandard.org/en/about/governance/who-runs-iati/)

---

## Our history ##

* [x] HTML5 

    ```
    Error: End tag main seen, but there were open elements.

    From line 459, column 9; to line 459, column 15

    ↩↩        </main>↩↩    

    Error: Unclosed element div.

    From line 150, column 1; to line 150, column 17

     </div>↩↩↩<div class="row">↩    <div
     ```

 ---

## Guidance Page ##

* [x] General visual/matching pattern lib
  * Should 'contact support' appear on all guidance pages? this is the PL equiv http://staging2.iatistandard.org/en/guidance/preparing-data/what-data-to-publish/
  * Spacing on contact form success looks wrong
  
<img width="784" alt="screen shot 2018-07-03 at 11 01 24" src="https://user-images.githubusercontent.com/8557782/42230358-b4ca7062-7ee0-11e8-9b9a-0ee9a97fff45.png">

* [x] Data
  * Is this page incomplete? `In this section:` http://staging2.iatistandard.org/en/guidance/preparing-data/what-data-to-publish/
  * Attachment option not present on form (I'm guessing this has been consciously removed/is out of scope)

---

## News ##

* [x] General visual/matching pattern lib
  * PL shows one featured article and 3 other articles (total 4), staging only shows 1 featured 2 other
  * No categories still shows category title, is this intentional/should it be hidden if not categories?
* [x] Data
  * There are 112 paginated pages with 3 items on each and no categories, I guess the data isn't ready?

---

## News page ##


* [x] General visual/matching pattern lib
  * Article text is too close to footer http://staging2.iatistandard.org/en/news/promoting-iati-data-at-world-press-freedom-day/

<img width="1039" alt="screen shot 2018-07-03 at 15 04 37" src="https://user-images.githubusercontent.com/8557782/42230350-ab831978-7ee0-11e8-8c99-99edd1815ef2.png">


---

## Events ##

* [x] No JS
  * calendar icon does not show (`icon.fallback.css`, same on PL)
* [x] Data
  * No event types - will there be? should the event type box be hidden if there are none?

---

## Event page ##

* [x] HTML5 
   ```
       Error: End tag main seen, but there were open elements.

    From line 315, column 9; to line 315, column 15

    ↩↩        </main>↩↩    

    Error: Unclosed element div.

    From line 155, column 3; to line 155, column 43

    ="row">↩  <div class="l-sidebar l-sidebar--mobile">↩    <

    Error: Unclosed element div.

    From line 154, column 1; to line 154, column 17

    ↩</div>↩↩↩<div class="row">↩  <di
    ```

* [x] Link clicks
  * 'Register your place' button does nothing http://staging2.iatistandard.org/en/events/register-now-for-members-assembly-2018-un-city-copenhagen-9-11/ - 

  ```
      Uncaught TypeError: Cannot read property 'top' of undefined
        at HTMLAnchorElement.<anonymous> (app.bundle.js:1)
        at HTMLAnchorElement.dispatch (app.bundle.js:2)
        at HTMLAnchorElement.m.handle (app.bundle.js:2)
  ```

  Works when there is no JS

---

## Website Link ##

* [x] Data
  * Title subheading is None - does it need a fallback, or to not appear at all?


---

**Comment by Daviniafffunction** [comment]
Moved to PL repo: https://github.com/IATI/IATI-Pattern-Library/issues/96
