### ISSUE TITLE
Add a sitemap.xml

### ISSUE THREAD

**Issue by andylolz** [IATI/preview-website#226]

**Comment by samuele-mattiuzzo** [comment]
This is code-complete, but our Sites need modification. We need the sitemaps to come out with the relevant hostname and not `localhost` (http://docs.wagtail.io/en/v2.1/reference/contrib/sitemaps.html#setting-the-hostname)

Currently, our live CMS Site's hostname is `localhost`, which will not be of any help once crawlers reach it.

@akmiller01 you did a lot of the *Ops/Apache conf stuff, how much breakage will we introduce if we just rename the hostname in that section? seems to be fine locally ("works on my machine" lol); otherwise the other option would be to extend Wagtail's sitemap template/view to always automatically fetch the host the app is being served from (so it becomes environment-agnostic and we won't lose any config/step if we move away from our current host)

**Comment by akmiller01** [comment]
@samuele-mattiuzzo , I don't think we're actually using the built-in sitename for anything else. So easiest solution is to just set it right in the CMS on production, I think.

**Comment by samuele-mattiuzzo** [comment]
Checked the apache conf file and the servers, you seem to be right, so we can just change it in the CMS indeed
